# This PodSecurityPolicy is specifically built for Google's COS AuditD PODs
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cos-auditd-logging-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  # Prevent containers from running as privileged
  privileged: false
  # Prevents a process in a containers from gaining elevated privileges
  allowPrivilegeEscalation: false
  allowedCapabilities: []
  volumes:
  - 'configMap'
  - 'hostPath'
  allowedHostPaths:
    - pathPrefix: "/"
    - pathPrefix: "/var/log"
      readOnly: true
    - pathPrefix: "/usr/lib64"
      readOnly: true
  hostNetwork: true
  hostIPC: false
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
